 on:
   push:
     branches:
       - main
     
 jobs:
   render:
     name: Render all READMEs
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: quarto-dev/quarto-actions/setup@v2
       - uses: quarto-dev/quarto-actions/render@v2
       - name: Commit results
         run: |
           git config --global user.email "culshawmaurer@arizona.edu"
           git config --global user.name "Michael Culshaw-Maurer"
           git add --force */README.md
           git add --force */read_me_files/ || echo "No files generated"
           git commit -m 'Render READMEs' || echo "No changes to commit"
           git push origin || echo "No changes to commit"
